import Head from "next/head";
import Message from  "../components/message";
import {useEffect, useState } from "react";
import {db} from "../utils/firebase";
export default function Home() {
  return (
    <div>
        <Head>
            <title>RealDiscuss</title>
            <meta content="width=device-width, initial-scale=1" name="viewport" />
            <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
        </Head> 
        <div className="my-12 text-lg font-medium">
            <h2> See what people are discussing </h2>
        </div>  
    </div>
    );
}
